delete from public.yuk_disposal_rules
where country_code = 'EE' and metadata->>'dataset' = 'estonia-national-2025';

insert into public.yuk_disposal_rules
  (country_code, jurisdiction, item_key, bin, destination, instructions, source_url, confidence, valid_from, metadata)
values
  ('EE', null, 'mixed', 'mixed municipal waste', 'municipal residual-waste collection', 'Use for household waste that does not belong in a separately collected stream.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/pakendid', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'packaging_plastic_metal_carton', 'plastic and metal packaging + beverage cartons', 'packaging collection', 'Empty packaging of its contents before placing it in the packaging stream.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/plast-ja-metallpakend-koos-joogikartongiga', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'glass_packaging', 'glass packaging', 'glass-packaging collection', 'Use for glass packaging. Other glass and ceramics belong in their appropriate separate streams.', 'https://www.kliimaministeerium.ee/jaatmete-liigiti-kogumine/klaaspakend', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'bio', 'bio-waste', 'bio-waste container or home composting', 'Remove food from packaging. Prefer loose collection, paper bags, or fully compostable bags that meet the required standard.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/koogi-ja-sooklajaatmed', 1, '2025-10-15', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'paper_cardboard', 'paper and cardboard', 'paper/cardboard collection', 'Keep paper and cardboard reasonably clean and dry and separate from packaging streams where required.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/pakendid', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'batteries', 'battery collection', 'retailer collection point, battery box, or waste station', 'Never place batteries or accumulators in ordinary household or packaging waste.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/patareid-ja-akud', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'electronics', 'electronic waste', 'retailer take-back or waste station', 'Keep electrical and electronic equipment out of ordinary household waste and use an approved take-back or collection route.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/pakendid', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'medicines', 'separate medicine collection', 'pharmacy, waste station, or hazardous-waste collection point', 'Unused and expired medicines require separate collection.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/ravimid', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'hazardous', 'hazardous-waste collection', 'waste station or hazardous-waste collection point', 'Do not place hazardous household waste in ordinary bins. Keep it separated and use an approved collection route.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/pakendid', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'textile', 'textile waste', 'textile-waste collection at a waste station or collection round', 'Keep reusable clothes in reuse channels; collect non-reusable textile waste separately where the local system provides it.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/pakendid', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}'),
  ('EE', null, 'bulky', 'bulky waste', 'waste station or local bulky-waste collection', 'Large household objects require a bulky-waste route rather than ordinary bins.', 'https://kliimaministeerium.ee/jaatmete-liigiti-kogumine/suurjaatmed', 1, '2025-10-20', '{"dataset":"estonia-national-2025","authority":"Estonian Ministry of Climate"}');
